name = "kellenfujimoto"
license = "MIT"
licenselink = "https://github.com/vimux/blank/blob/master/LICENSE"
description = "Theme for kellenfujimoto.com"
homepage = "https://github.com/rakenodiax/blank/"
tags = ["blog"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "Kellen Frodelius-Fujimoto"
  homepage = "https://github.com/rakenodiax"
